# Generated by Django 4.2.1 on 2023-05-28 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0006_rename_is_particpant_customuser_is_participant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_judge',
            field=models.BooleanField(default=False, null=True, verbose_name='judge status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_participant',
            field=models.BooleanField(default=False, null=True, verbose_name='particpant status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(null=True, default=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
